import Head from "next/head";
import Navbar from "@/components/navbar";
import styles from '@/styles/AboutUs.module.css';
import Footer from "@/components/Footer";
import Gallery from "@/components/Gallery";
import Assistant from "@/components/Assistant";
import DocumentGallery from "@/components/DocumentGallery";
export default function AboutUs (){
    return(
        <>
            <Head>
                <title>Bargad NGO</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="preconnect" href="https://fonts.googleapis.com"/>
                <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true"/>
                <link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap" rel="stylesheet"/>
            </Head>
            <div className={styles.container}>
                <Assistant/>
                <div className={styles.topDiv} style={{backgroundImage:'/mission.jpg'}}>
                         <Navbar/>
                </div>
                        
                <div className={styles.newsDiv}>
                  <div className={styles.newsDiv_top}>

                             <h2 className={styles.newsDiv_top_header}>Learn About Bargad</h2>

                  </div>
                  <div className={styles.newsDiv_bottom}>   
                       
                        <div className={styles.mission_div}>
                                    {/* <div className={styles.newsDiv_block_second_left}>
                                                <div className={styles.newsDiv_block_second_left_photo}>
                                                        <img src="/jalutsav.jpg" className={styles.newsDiv_block_second_left_photo_image} width={150} height={150}/>
                                                </div>
                                    </div> */}

                                    <div className={styles.newsDiv_block_second_right}>
                                            <div className={styles.newsDiv_block_second_right_top}>
                                                <h2 className={styles.newsDiv_block_header}>Our Mission</h2>
                                                <div className={styles.newsDiv_block_spacer}></div>
                                            </div>

                                            <div className={styles.newsDiv_block_second_right_bottom}>
                                                <p className={styles.newsDiv_block_paragraph}>BARGAD keeps going to people, organize and carry forward the Vedic Nacher Dhamma way of life, working for a convergence of multiple development initiatives aiming to improve the socio-economic condition of the poor people; bringing together the value oriented individuals & groups to work collectively for promotion of alternative development models; and Inspiring and involving young leadership for effective management of human resources to address developmental needs.</p>
                                            </div>
                                    </div>
                                    {/* <br/> we run a school and implement various developmental activities in 50 villages, aiming to provide quality education and reduce rural migration. */}
                        </div>

                        <div className={styles.newsDiv_block}>
                                <div className={styles.newsDiv_block_left}>
                                        <div className={styles.newsDiv_block_left_top}>
                                            <h2 className={styles.newsDiv_block_header}>Our Vision</h2>
                                            <div className={styles.newsDiv_block_spacer}></div>
                                        </div>

                                        <div className={styles.newsDiv_block_left_bottom}>
                                            <p className={styles.newsDiv_block_paragraph}>BARGAD Bharatiye Altertiye Research Growth and Diversity  envisions a just and equitable society based on self-reliance, social well-being and sustainable development following the Vedic Nacher Dhamma principles.
                                           </p>
                                        </div>
                                </div>
                                {/* <div className={styles.newsDiv_block_right}>
                                            <div className={styles.newsDiv_block_right_photo}>
                                                    <img src="/vision.JPG" className={styles.newsDiv_block_right_photo_image} width={150} height={150}/>
                                            </div>
                                </div> */}
                        </div>

                       





                                

                    </div>
                       

                </div>
                <div className={styles.infoDiv}>
                            {/* <div className={styles.infoDiv_top}>
                                <h2 className={styles.infoDiv_top_header}>Our Capacity And Experience</h2>
                                <div className={styles.infoDiv_spacer}></div>
                                <div className={styles.infoDiv_top_description}>
                                    <p className={styles.infoDiv_top_paragraph}>Although officially registered in 2020, our organization has a long history of impactful work, having operated informally for many years. Over this time, we have built a dedicated and experienced team. Our workforce includes 18 rural development workers and resource persons, along with 7 project-specific training staff, bringing our total team to 25 skilled professionals.</p>
                                </div>
                            </div> */}
                            <div className={styles.infoDiv_bottom}>
                                 <h2 className={styles.infoDiv_top_header}>Our Values</h2>
                                <div className={styles.infoDiv_spacer}></div>
                                <div className={styles.infoDiv_top_description}>
                                    <p className={styles.infoDiv_top_paragraph}>At Bargad NGO, we encourage the following values to be upheld both individually and organizationally:

                                        </p>
                                    <ul className={styles.infoDiv_bottom_list}>
                                        <li>Truth & Non-Violence</li>
                                        <li> Self-reliance</li>
                                        <li> Human Dignity</li>
                                        <li> Transparency</li>
                                        <li>Participatory Development</li>
                                       
                                        
                                    </ul>
                                </div>
                            </div>

                            <div className={styles.infoDiv_bottom}>
                                 <h2 className={styles.infoDiv_top_header}>Strategy</h2>
                                <div className={styles.infoDiv_spacer}></div>
                                <div className={styles.infoDiv_top_description}>
                                    <p className={styles.infoDiv_top_paragraph}>At Bargad NGO, our strategy is centered on the following approaches to drive impactful change:

                                        </p>
                                    <ul className={styles.infoDiv_bottom_list}>
                                        <li> Promoting People&apos; Participation</li>
                                        <li> Partnership and coalition building</li>
                                        <li> Mobilization of the youth for peace, development and social harmony</li>
                                        <li> Pressure Group Formation for policy & programme advocacy</li>
                                        <li> Capacity Building</li>               
                                        <li> Education and Awareness Campaign</li>
                                        <li> Networking, Catalyzing and Synergizing development efforts</li>
                                        
                                       
                                       
                                        
                                    </ul>
                                </div>
                            </div>

                            <div className={styles.infoDiv_bottom}>
                                 <h2 className={styles.infoDiv_top_header}>Expertise and Best Practices</h2>
                                <div className={styles.infoDiv_spacer}></div>
                                <div className={styles.infoDiv_top_description}>
                                    <p className={styles.infoDiv_top_paragraph}>At Bargad NGO, our best practices and expertise are rooted in the following key areas:

                                        </p>
                                    <ul className={styles.infoDiv_bottom_list}>
                                        <li>Action Research </li>
                                        <li>Lobby & Advocacy Campaign and</li>
                                        <li>Networking</li>
                                     
                                       
                                        
                                    </ul>
                                </div>
                            </div>

                            <div className={styles.infoDiv_bottom}>
                                 <h2 className={styles.infoDiv_top_header}>Thematic Areas</h2>
                                <div className={styles.infoDiv_spacer}></div>
                                <div className={styles.infoDiv_top_description}>
                                    <p className={styles.infoDiv_top_paragraph}>At Bargad NGO, we focus on the following thematic areas to drive our mission forward:

                                        </p>
                                    <ul className={styles.infoDiv_bottom_list}>
                                        <li>Livelihood & Food Security</li>
                                        <li>Skill Development & Capacity Building</li>
                                        <li>Child Care & Education</li>
                                        <li>Health & Sanitation</li>
                                        <li>Gender Justice & Empowerment</li>
                                        <li>Disability</li>
                                        <li>Environment & Natural Resource Management</li>
                                        <li>Peace & Social Harmony</li>
                                        <li>Emergency Response</li>
                                       
                                        
                                    </ul>
                                </div>
                            </div>

                            <div className={styles.infoDiv_top}>
                                <h2 className={styles.infoDiv_top_header}>Operational Periphery</h2>
                                <div className={styles.infoDiv_spacer}></div>
                                <div className={styles.infoDiv_top_description}>
                                    <p className={styles.infoDiv_top_paragraph}>VSP Activities are carried out in the State of Odisha and association with others NGOs in several States of India to materialize the organizational Vision for a just and economically prosperous society.</p>
                                </div>
                            </div>


                            <div className={styles.infoDiv_bottom}>
                                 <h2 className={styles.infoDiv_top_header}>Success & Milestones</h2>
                                <div className={styles.infoDiv_spacer}></div>
                                <div className={styles.infoDiv_top_description}>
                                    <p className={styles.infoDiv_top_paragraph}>At Bargad NGO, our success and milestones are reflected in the following achievements:

                                        </p>
                                    <ul className={styles.infoDiv_bottom_list}>
                                        <li> Distribution of 120 Acre of Bhoodan Land to the landless Poor in program in Association with Vinoba  <span>   </span> Seva Pratisthan </li>
                                        <li> Training to 3000 PRI members on Local Self Governance</li>
                                        <li> Training to 500 Young Peace Workers</li>
                                        <li> Training to 2500 farmers on improved agricultural practices</li>
                                        <li> Training to 300 Disaster Mitigation Team members for Emergency Response</li>
                                        <li> Training to 600 Youth Club members on community development</li>
                                        <li> Self employment assistance to 150 visually impaired women</li>
                                        <li> Jobs facilitation to more than 1200 unemployment Youth</li>
                                        <li> Capacity Building of 550 women SHGs for self employment</li>
                                        <li> Training 250 CHW (Community Health Workers) on Mother & Child care</li>
                                        <li> Formation of over 150 peace clubs in Schools</li>
                                        <li> Training to 400 Vaidyas ( traditional healers) on Ayurveda</li>
                                        <li> Relief support to 6000 families during COVID Pandemic</li>
                                        <li> National constructive campaign “BAPASI” </li>
                                        <li> Awareness program  “Delhi Kite Festival” Workshop Manodasa to Manoratana Happiness Therapy Campaign  on occasion of international kite festival 2022  </li>
                                       
                                        
                                    </ul>
                                </div>
                            </div>

                            <div className={styles.infoDiv_bottom}>
                                 <h2 className={styles.infoDiv_top_header}>Networking & Alliance</h2>
                                <div className={styles.infoDiv_spacer}></div>
                                <div className={styles.infoDiv_top_description}>
                                    <p className={styles.infoDiv_top_paragraph}>At Bargad NGO, our network and alliances are strengthened through the following collaborations:

                                        </p>
                                    <ul className={styles.infoDiv_bottom_list}>
                                        <li> Commonwealth Foundation Londan UK Seva Pratisthan </li>
                                        <li> Member of South Asia Fraternity(SAF)</li>
                                        <li> Member of Gandhi Global Foundation(GGF)</li>
                                        <li> Lok Nayak Samman by LJPN International Study Centre,New Delhi</li>
                                        <li> Member of Acharyaul- an intellectual body of all India level</li>
                                        <li> Core member of Vinoba Seva Pratisthan (VSP)” a coalition of civil society organizations of Odisha</li>
                                        <li> Core member of “ Bhartiye Nagarik Samaj(BHNAS)” a coalition of civil society organizations of Bundelkhand</li>
                                        <li> Core Member of “National integration Campaign (NIC)” a Pen India  AKHAND BHARAT Awareness movement for peace building</li>
                                        <li> Member of Neheru Yuva Kendra Sanghathan(NYKS)</li>
                                        <li> Advisor “Odisha Womens Association for Visually Handcapped” for strengthening their efficiency</li>
                                        <li> Involvement with state level campaign on child labour as “ Liberated Childhood Movement”</li>
                                    
                                       
                                        
                                    </ul>
                                </div>
                            </div>

                            <div className={styles.infoDiv_bottom}>
                                 <h2 className={styles.infoDiv_top_header}>Awards & Recognition</h2>
                                <div className={styles.infoDiv_spacer}></div>
                                <div className={styles.infoDiv_top_description}>
                                    <p className={styles.infoDiv_top_paragraph}>At Bargad NGO, our awards and recognition highlight our commitment and impact:

                                        </p>
                                    <ul className={styles.infoDiv_bottom_list}>
                                        <li> National Harmony Award by Indian Solidarity Council,New Delhi </li>
                                        <li> Lok Nayak Samman by LJPN International Study Centre,New Delhi</li>
                                        <li> Gopabandhu Samman by The Samaj, an Odia Premier Daily at Bhubaneswar</li>
                                        <li>  Maja Koene Award by CESCI Foundation of India & Switzerland</li>
                                        <li> Wockhardt Popular Award on Women Rights & Empowerment , Mumbai</li>
                                        <li> Productivity Enhancement for NGOs on National Production” by National Productivity Council (NPC)</li>
                                        <li> Sister Nivedita Award by Swami Vivekananda Foundation, West Bengal</li>
                                      
                                    
                                       
                                        
                                    </ul>
                                </div>
                            </div>

                            <div className={styles.infoDiv_bottom}>
                                 <h2 className={styles.infoDiv_top_header}>Guiding Values & Principles</h2>
                                <div className={styles.infoDiv_spacer}></div>
                                <div className={styles.infoDiv_top_description}>
                                    <p className={styles.infoDiv_top_paragraph}>At Bargad NGO, our guiding values and principles are reflected in our commitment to:

                                        </p>
                                    <ul className={styles.infoDiv_bottom_list}>
                                        <li> Concern for the development of the least person of the society </li>
                                        <li> Tolerance, acceptance and respect for all faiths and belief</li>
                                       
                                    
                                       
                                        
                                    </ul>
                                </div>
                            </div>

                            <div className={styles.infoDiv_bottom}>
                                 <h2 className={styles.infoDiv_top_header}>Objectives</h2>
                                <div className={styles.infoDiv_spacer}></div>
                                <div className={styles.infoDiv_top_description}>
                                    <p className={styles.infoDiv_top_paragraph}>At Bargad NGO, our objectives guide our efforts towards impactful change:

                                        </p>
                                    <ul className={styles.infoDiv_bottom_list}>
                                        <li> To educate people on national integration, solidarity, peace, harmony and world fraternity </li>
                                        <li> To promote and exchange socio- cultural values, customs and ideas among youths of different countries</li>
                                        <li> To respect and observe national day of different counties and other bilateral programmes</li>
                                        <li> To promote a society where all people irrespective of their caste, creed, gender, race and religion will have equal rights and opportunities to lead a dignified life</li>
                                        <li> Promote the constructive actions expounded by Bapu and enabling self reliance programmes for marginalized people</li>
                                        <li> Preserve and protect the environment for future generation by adopting eco-friendly actions</li>
                                        <li> To promote Ayurveda, Yoga, Naturopathy, Homeopathy and other form of alternative medicines for health care of people</li>
                                        <li> To promote library, reading room and book banks for qualitative and moral education among students</li>
                                        <li> To organize various talent and skill development programs among children and promote them to lead a dignified life</li>
                                        <li> To conduct research, study and publish books, magazine, journals for promotion of Gandhian Values</li>
                                        <li> To support organic agriculture and farming to marginalized farmers and farming communities</li>
                                        <li> To support the poor and disadvantaged people for improving their traditional occupation and livelihood pattern</li>
                                        <li> To organize or facilitate for various training, seminars, events on topics relevant to human resource development, Leadership development, youth development, skill development, innovation and sustainable development</li>
                                        <li> To improve socio-economic status and dignity of women through holistic empowerment and gender justice programmes</li>
                                        <li> To institute awards, fellowships for volunteers, social workers, and other dignitaries who has contributed for the welfare of the society in different spectrum of life</li>
                                        <li> To create socio cultural awareness through publication of periodicals, audio, visuals documentary, film & TV serials etc</li>
                                    
                                       
                                        
                                    </ul>
                                </div>
                            </div>

                            <div className={styles.infoDiv_bottom}>
                                 <h2 className={styles.infoDiv_top_header}>Future Plan</h2>
                                <div className={styles.infoDiv_spacer}></div>
                                <div className={styles.infoDiv_top_description}>
                                    <p className={styles.infoDiv_top_paragraph}>BARGAD has planned to set up a model institution by establishing a center called Kakshi Rishi  Kendra in BUNDELKHAND & Odisha. It has also planned to establish the following institutions there as..

                                        </p>
                                    <ul className={styles.infoDiv_bottom_list}>
                                        <li> Training Centre (Krishi & Rishi Kendra) </li>
                                        <li> Modern and Vedic  Educational Ashram for Poor Children </li>
                                        <li> Ayurveda Excellence Centre </li>
                                        {/* <li> To promote a society where all people irrespective of their caste, creed, gender, race and religion will have equal rights and opportunities to lead a dignified life</li>
                                        <li> Promote the constructive actions expounded by Bapu and enabling self reliance programmes for marginalized people</li>
                                        <li> Preserve and protect the environment for future generation by adopting eco-friendly actions</li>
                                        <li> To promote Ayurveda, Yoga, Naturopathy, Homeopathy and other form of alternative medicines for health care of people</li>
                                        <li> To promote library, reading room and book banks for qualitative and moral education among students</li>
                                        <li> To organize various talent and skill development programs among children and promote them to lead a dignified life</li>
                                        <li> To conduct research, study and publish books, magazine, journals for promotion of Gandhian Values</li>
                                        <li> To support organic agriculture and farming to marginalized farmers and farming communities</li>
                                        <li> To support the poor and disadvantaged people for improving their traditional occupation and livelihood pattern</li>
                                        <li> To organize or facilitate for various training, seminars, events on topics relevant to human resource development, Leadership development, youth development, skill development, innovation and sustainable development</li>
                                        <li> To improve socio-economic status and dignity of women through holistic empowerment and gender justice programmes</li>
                                        <li> To institute awards, fellowships for volunteers, social workers, and other dignitaries who has contributed for the welfare of the society in different spectrum of life</li>
                                        <li> To create socio cultural awareness through publication of periodicals, audio, visuals documentary, film & TV serials etc</li>
                                     */}
                                       
                                        
                                    </ul>
                                </div>
                            </div>



                            



                            

                </div>
                {/* <div className={styles.galleryHolder}>
                    <div className={styles.galleryHolder_top}>
                        <div className={styles.galleryHolder_top_content}>
                         <h2 className={styles.galleryHolder_top_header}>Photo Gallery</h2>
                        </div>
                    </div>
                     <Gallery/>

                    
                </div> */}

                {/* <div className={styles.galleryHolder}>
                    <div className={styles.galleryHolder_top}>
                        <div className={styles.galleryHolder_top_content}>
                         <h2 className={styles.galleryHolder_top_header}>Certifications & Reports</h2>
                        </div>
                    </div>
                     <DocumentGallery/>

                    
                </div> */}
                
                <Footer/>
            
            </div>
        </>
    )
}
