import Head from "next/head";
import Navbar from "@/components/navbar";
import styles from '@/styles/Projects.module.css';
import Footer from "@/components/Footer";
import Assistant from "@/components/Assistant";
export default function Projects (){
    return(
        <>  
            <Head>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="preconnect" href="https://fonts.googleapis.com"/>
                <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true"/>
                <link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap" rel="stylesheet"/>
                </Head>

                <div className={styles.container}>
                <Assistant/>
                    <div className={styles.topDiv}>
                         <Navbar/>
                    </div>
                    <div className={styles.newsDiv}>
                            <div className={styles.newsDiv_top}>

                                        <h2 className={styles.newsDiv_top_header}>Projects by Bergad</h2>

                            </div>
                            <div className={styles.newsDiv_bottom}>
                       
                                    <div className={styles.newsDiv_block_second}>
                                                <div className={styles.newsDiv_block_second_left}>
                                                            <div className={styles.newsDiv_block_second_left_photo}>
                                                                    <img src="/project.jpg" className={styles.newsDiv_block_second_left_photo_image} width={150} height={150}/>
                                                            </div>
                                                </div>

                                                <div className={styles.newsDiv_block_second_right}>
                                                        <div className={styles.newsDiv_block_second_right_top}>
                                                            <h2 className={styles.newsDiv_block_header}>Krushak Vikash Samiti</h2>
                                                            <div className={styles.newsDiv_block_spacer}></div>
                                                        </div>

                                                        <div className={styles.newsDiv_block_second_right_bottom}>
                                                            <p>The BARGAD Foundation's Krushak Vikash Samiti (KVS) in Mayurbhanj, Odisha, supports small farmers with training in advanced agricultural techniques and essential resources to enhance productivity and livelihoods.</p>
                                                        </div>
                                                </div>
                                                
                                                {/* <br/> we run a school and implement various developmental activities in 50 villages, aiming to provide quality education and reduce rural migration. */}
                                    </div>
                                    <div className={styles.newsDiv_block}>
                                            <div className={styles.newsDiv_block_left}>
                                                    <div className={styles.newsDiv_block_left_top}>
                                                        <h2 className={styles.newsDiv_block_header}>Supporting Women</h2>
                                                        <div className={styles.newsDiv_block_spacer}></div>
                                                    </div>

                                                    <div className={styles.newsDiv_block_left_bottom}>
                                                        <p>CBOs and SHGs support women's income generation through group farming training and sustainable agriculture practices for small farmers. The initiative promotes organic farming and community-managed grain banks.</p>
                                                    </div>
                                            </div>
                                            <div className={styles.newsDiv_block_right}>
                                                        <div className={styles.newsDiv_block_right_photo}>
                                                                <img src="/project2.jpg" className={styles.newsDiv_block_right_photo_image} width={150} height={150}/>
                                                        </div>
                                            </div>
                                    </div>
                                    <div className={styles.newsDiv_block_second}>
                                                <div className={styles.newsDiv_block_second_left}>
                                                            <div className={styles.newsDiv_block_second_left_photo}>
                                                                    <img src="/checkup.jpg" className={styles.newsDiv_block_second_left_photo_image} width={150} height={150}/>
                                                            </div>
                                                </div>

                                                <div className={styles.newsDiv_block_second_right}>
                                                        <div className={styles.newsDiv_block_second_right_top}>
                                                            <h2 className={styles.newsDiv_block_header}>Checkup Camps</h2>
                                                            <div className={styles.newsDiv_block_spacer}></div>
                                                        </div>

                                                        <div className={styles.newsDiv_block_second_right_bottom}>
                                                            <p>Free check-up camp for leprosy and skin disease patients will be held every month, starting January 28, 2017, on World Leprosy Day, in Delhi NCR.</p>
                                                        </div>
                                                </div>
                                                
                                                {/* <br/> we run a school and implement various developmental activities in 50 villages, aiming to provide quality education and reduce rural migration. */}
                                    </div>
                                    <div className={styles.newsDiv_block}>
                                            <div className={styles.newsDiv_block_left}>
                                                    <div className={styles.newsDiv_block_left_top}>
                                                        <h2 className={styles.newsDiv_block_header}>Tree Plantation</h2>
                                                        <div className={styles.newsDiv_block_spacer}></div>
                                                    </div>

                                                    <div className={styles.newsDiv_block_left_bottom}>
                                                        <p>Plantation of fruit trees across India to combat deforestation, with a target of 100,000 trees successfully achieved.</p>
                                                    </div>
                                            </div>
                                            <div className={styles.newsDiv_block_right}>
                                                        <div className={styles.newsDiv_block_right_photo}>
                                                                <img src="/plantation.jpg" className={styles.newsDiv_block_right_photo_image} width={150} height={150}/>
                                                        </div>
                                            </div>
                                    </div>
                                    <div className={styles.newsDiv_block_second}>
                                                <div className={styles.newsDiv_block_second_left}>
                                                            <div className={styles.newsDiv_block_second_left_photo}>
                                                                    <img src="/cleanup.jpeg" className={styles.newsDiv_block_second_left_photo_image} width={150} height={150}/>
                                                            </div>
                                                </div>

                                                <div className={styles.newsDiv_block_second_right}>
                                                        <div className={styles.newsDiv_block_second_right_top}>
                                                            <h2 className={styles.newsDiv_block_header}>Senva Pond Clean Intiative</h2>
                                                            <div className={styles.newsDiv_block_spacer}></div>
                                                        </div>

                                                        <div className={styles.newsDiv_block_second_right_bottom}>
                                                            <p>In August 2015, BARGAD and Yamuna Rakshak Dal cleaned Senva Pond near Vrindavan, improving turtle habitat and providing clean water for villagers. The initiative featured the first Yamuna Aarti to promote tourism and introduced a mini biogas plant, recognized by Shri Dharmendra Pradhan.</p>
                                                        </div>
                                                </div>
                                                
                                                {/* <br/> we run a school and implement various developmental activities in 50 villages, aiming to provide quality education and reduce rural migration. */}
                                    </div>
                                    
                                    
                                   
                            </div>
                    </div>
                    <Footer/>
                </div>
        </>
    )
}